#!/usr/bin/env bash
# tools/setup.sh — 部署自检 + 配置生成（bash 版，Git Bash 用）| Deploy & self-configure
# 1) 探测 MinGW 工具链  2) 写 tools/toolchain.config  3) 从模板生成 .vscode/launch.json / c_cpp_properties.json
# 用法 Usage: tools/setup.sh   （部署到新位置/新机器后跑一次）

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG="$SCRIPT_DIR/toolchain.config"

# ---------- 1) 探测工具链 ----------
if [ -z "$MINGW_BIN" ] && [ -f "$CONFIG" ]; then
  MINGW_BIN="$(grep -E '^MINGW_BIN=' "$CONFIG" | head -1 | sed 's/^MINGW_BIN=//')"
fi
if [ -z "$MINGW_BIN" ]; then
  for c in "D:/XC_workspace/msys64/mingw64/bin" "/c/msys64/mingw64/bin" "/d/msys64/mingw64/bin" "/c/tools/msys64/mingw64/bin"; do
    if [ -x "$c/g++.exe" ] && [ -x "$c/gdb.exe" ]; then
      MINGW_BIN="$c"
      break
    fi
  done
fi
if [ -z "$MINGW_BIN" ]; then
  echo "✗ 未检测到 MinGW 工具链 (g++.exe / gdb.exe)。" >&2
  echo "  请手动把工具链 bin 路径写入 $CONFIG 的 MINGW_BIN= 行，或设置环境变量 MINGW_BIN。" >&2
  exit 1
fi
echo "==> 工具链 Toolchain: $MINGW_BIN"
"$MINGW_BIN/g++.exe" --version | head -1

# ---------- 2) write config ----------
{
  echo "# Toolchain location -- generated by tools/setup.sh, edit to change"
  echo "# Priority: env MINGW_BIN > this file > auto-detect"
  echo "MINGW_BIN=$MINGW_BIN"
} > "$CONFIG"
echo "==> 已写入 $CONFIG"

# ---------- 3) 生成 .vscode 配置 ----------
FWD="${MINGW_BIN//\\//}"
for pair in ".vscode/launch.json:.vscode/launch.json.template" ".vscode/c_cpp_properties.json:.vscode/c_cpp_properties.json.template"; do
  out="$ROOT/${pair%%:*}"; tpl="$ROOT/${pair##*:}"
  if [ -f "$tpl" ]; then
    sed -e "s|__MINGW_BIN__|$FWD|g" "$tpl" > "$out"
    echo "==> 已生成 $out"
  else
    echo "[跳过] 模板不存在: $tpl"
  fi
done
echo "==> 完成 Done。重启 VS Code（或重新加载窗口）后调试配置生效。"
