@echo off
rem tools\setup.bat -- Deploy & self-configure: detect MinGW, write config, generate .vscode files.
rem Usage: tools\setup.bat   (run once after deploying to a new location / machine)
rem NOTE: this file is ASCII-only on purpose; cmd.exe parses batch files in the ANSI codepage (GBK on zh-CN),
rem       and UTF-8 Chinese bytes can corrupt command parsing.
setlocal EnableDelayedExpansion

set "ROOT=%~dp0.."
set "CONFIG=%~dp0toolchain.config"

rem ---------- 1) detect toolchain ----------
if not defined MINGW_BIN if exist "%CONFIG%" (
  for /f "usebackq tokens=1,* delims==" %%A in ("%CONFIG%") do (
    if "%%A"=="MINGW_BIN" set "MINGW_BIN=%%B"
  )
)
if not defined MINGW_BIN (
  for %%D in ("D:\XC_workspace\msys64\mingw64\bin" "C:\msys64\mingw64\bin" "C:\tools\msys64\mingw64\bin") do (
    if exist "%%~D\g++.exe" if exist "%%~D\gdb.exe" set "MINGW_BIN=%%~D"
  )
)
if not defined MINGW_BIN (
  echo [ERROR] MinGW toolchain not found ^(g++.exe / gdb.exe^).
  echo         Edit MINGW_BIN= in %CONFIG%, or set env var MINGW_BIN.
  exit /b 1
)
echo ==^> Toolchain: %MINGW_BIN%
"%MINGW_BIN%\g++.exe" --version 2>nul | findstr /b "g++"

rem ---------- 2) write config ----------
> "%CONFIG%" echo # Toolchain location -- generated by tools\setup.bat, edit to change
>> "%CONFIG%" echo # Priority: env MINGW_BIN ^> this file ^> auto-detect
>> "%CONFIG%" echo MINGW_BIN=%MINGW_BIN%
echo ==^> Wrote %CONFIG%

rem ---------- 3) generate .vscode files ----------
set "FWD=!MINGW_BIN:\=/!"
call :genfile "%ROOT%\.vscode\launch.json" "%ROOT%\.vscode\launch.json.template"
call :genfile "%ROOT%\.vscode\c_cpp_properties.json" "%ROOT%\.vscode\c_cpp_properties.json.template"
echo ==^> Done. Reload VS Code window for the debug config to take effect.
exit /b 0

:genfile
rem replace __MINGW_BIN__ in a template with the actual toolchain path (forward-slash form)
if not exist "%~2" (
  echo [skip] template missing: %~2
  exit /b 0
)
> "%~1" echo.
for /f "usebackq delims=" %%L in ("%~2") do (
  set "line=%%L"
  set "line=!line:__MINGW_BIN__=%FWD%!"
  >> "%~1" echo !line!
)
echo ==^> Generated %~1
exit /b 0
